apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-agent
  namespace: gocd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: gocd-agent
    spec:
      containers:
        - name: gocd-agent
          image: altairsix/gocd-agent:17.2.0
          env:
            - name: GO_SERVER
              value: gocd-server
            - name: MYSQL_USER
              value: gocd
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: gocd
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ssh-git
                  key: "id_rsa"
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: ssh-git
                  key: "id_rsa.pub"
          volumeMounts:
            - name: docker-bin
              mountPath: /usr/bin/docker
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: usr-lib
              mountPath: /usr/lib/x86_64-linux-gnu
            - name: lib
              mountPath: /lib/x86_64-linux-gnu
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: gocd
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: gocd
        - name: memcache
          image: memcached
          ports:
            - containerPort: 11211
        - name: dynamodb
          image: savaki/dynamodb:latest
          ports:
            - containerPort: 8000
      volumes:
        - name: docker-bin
          hostPath:
            path: /usr/bin/docker
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: usr-lib
          hostPath:
            path: /usr/lib/x86_64-linux-gnu
        - name: lib
          hostPath:
            path: /lib/x86_64-linux-gnu

