apiVersion: v1
kind: Service
metadata:
  name: gocd-server
  namespace: gocd
spec:
  ports:
    - port: 443
      targetPort: 8154
      name: https
  selector:
    service: gocd-server
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 71.198.73.163/32

