apiVersion: v1
kind: Service
metadata:
  name: gocd-server
  namespace: gocd
spec:
  ports:
    - port: 8154
      targetPort: 8154
      name: http
    - port: 8153
      targetPort: 8153
      name: https
  selector:
    service: gocd-server

