apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-server
  namespace: gocd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: gocd-server
    spec:
      containers:
        - name: gocd-server
          image: altairsix/gocd-server:16.12.0
          env:
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ssh-git
                  key: "id_rsa"
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: ssh-git
                  key: "id_rsa.pub"
          ports:
            - containerPort: 8153
            - containerPort: 8154
          volumeMounts:
            - name: gocd-etc-go
              mountPath: /etc/go
            - name: gocd-var-lib
              mountPath: /var/lib/go-server
            - name: gocd-var-log
              mountPath: /var/log/go-server
          securityContext:
            privileged: true
      volumes:
        - name: gocd-etc-go
          awsElasticBlockStore:
            volumeID: vol-0a2e40cdbe775300b
            fsType: ext4
        - name: gocd-var-lib
          awsElasticBlockStore:
            volumeID: vol-02fd443fd783ecf29
            fsType: ext4
        - name: gocd-var-log
          awsElasticBlockStore:
            volumeID: vol-02847c1f8c30751bc
            fsType: ext4

