apiVersion: v1
kind: Service
metadata:
  name: gocd-server
spec:
  ports:
    - port: 443
      targetPort: 8154
      name: ssl
    - port: 8154
      targetPort: 8154
      name: agent
  selector:
    service: gocd-server
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 50.131.228.169/32

